-- Add diverse debate topics to the topics table
INSERT INTO public.topics (title, description, category, difficulty) VALUES
('Should social media platforms be held responsible for the mental health of their users?', 'Debate the extent to which social media companies should be accountable for user wellbeing and mental health outcomes.', 'technology', 'intermediate'),
('Is artificial intelligence a threat to human employment?', 'Examine whether AI advancement will lead to mass unemployment or create new job opportunities.', 'technology', 'intermediate'),
('Should there be a universal basic income?', 'Discuss the feasibility and benefits of providing unconditional income to all citizens.', 'economics', 'advanced'),
('Is climate change the most pressing issue of our time?', 'Evaluate whether climate change should be the top global priority compared to other challenges.', 'environment', 'intermediate'),
('Should voting be mandatory in democratic societies?', 'Debate whether compulsory voting strengthens or weakens democratic participation.', 'politics', 'intermediate'),
('Is online education as effective as traditional classroom learning?', 'Compare the effectiveness of digital versus in-person educational methods.', 'education', 'beginner'),
('Should genetic engineering in humans be allowed?', 'Discuss the ethical implications and potential benefits of human genetic modification.', 'science', 'advanced'),
('Is capitalism the best economic system?', 'Evaluate capitalism against alternative economic models for societal benefit.', 'economics', 'advanced'),
('Should athletes be allowed to use performance-enhancing drugs?', 'Debate the ethics and fairness of PEDs in competitive sports.', 'sports', 'intermediate'),
('Is space exploration worth the cost?', 'Examine whether space programs justify their expense given earthly problems.', 'science', 'intermediate'),
('Should hate speech be protected under free speech?', 'Balance free expression rights against protection from harmful speech.', 'politics', 'advanced'),
('Is nuclear energy the solution to climate change?', 'Evaluate nuclear power as a clean energy alternative despite safety concerns.', 'environment', 'intermediate'),
('Should standardized testing be eliminated?', 'Debate whether standardized tests help or harm educational assessment.', 'education', 'intermediate'),
('Is social media doing more harm than good?', 'Weigh the benefits and drawbacks of social media platforms on society.', 'technology', 'beginner'),
('Should college education be free for everyone?', 'Discuss the feasibility and impact of universal free higher education.', 'education', 'intermediate'),
('Is privacy dead in the digital age?', 'Examine whether meaningful privacy can exist with modern technology.', 'technology', 'intermediate'),
('Should wealthy nations accept more refugees?', 'Debate the moral and practical obligations regarding refugee assistance.', 'politics', 'intermediate'),
('Is working from home better than office work?', 'Compare remote work versus traditional office environments for productivity and wellbeing.', 'economics', 'beginner'),
('Should violent video games be banned?', 'Evaluate the relationship between violent gaming and real-world behavior.', 'technology', 'beginner'),
('Is traditional marriage still relevant?', 'Examine the role and importance of marriage in modern society.', 'social', 'intermediate'),
('Should we colonize Mars?', 'Debate the necessity and feasibility of establishing human settlements on Mars.', 'science', 'advanced'),
('Is fast fashion destroying the environment?', 'Examine the environmental impact of rapid clothing production and consumption.', 'environment', 'intermediate'),
('Should cryptocurrency replace traditional currency?', 'Evaluate digital currencies as alternatives to government-issued money.', 'economics', 'advanced'),
('Is artificial meat the future of food?', 'Discuss lab-grown meat as a solution to environmental and ethical concerns.', 'science', 'intermediate'),
('Should parents be licensed before having children?', 'Debate whether parenting requires formal qualification and oversight.', 'social', 'advanced'),
('Is cancel culture beneficial or harmful?', 'Examine the practice of boycotting individuals for controversial statements or actions.', 'social', 'intermediate'),
('Should animals have the same rights as humans?', 'Debate the extent of rights that should be granted to non-human animals.', 'ethics', 'intermediate'),
('Is democracy the best form of government?', 'Evaluate democratic systems against alternative forms of governance.', 'politics', 'advanced'),
('Should we ban single-use plastics completely?', 'Discuss the environmental necessity versus practical challenges of eliminating disposable plastics.', 'environment', 'beginner'),
('Is homeschooling better than public education?', 'Compare home-based learning with traditional school systems for child development.', 'education', 'intermediate')